######################################################################
# Automatically generated by qmake (2.01a) Sat May 10 11:27:58 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
